# Generated by Django 3.2.19 on 2023-05-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_advertisement_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='url',
        ),
    ]
