# Generated by Django 3.2.19 on 2023-05-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_remove_advertisement_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='user',
            new_name='created_by',
        ),
    ]
