# Generated by Django 3.2.19 on 2023-06-04 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0004_rename_user_advertisement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
